"""empty message

Revision ID: 7e5e119938e6
Revises: e5329a0aad08
Create Date: 2022-10-30 19:55:05.131729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5e119938e6'
down_revision = 'e5329a0aad08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###
