"""empty message

Revision ID: b070bb2696a4
Revises: 7e5e119938e6
Create Date: 2022-10-31 16:45:18.838009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b070bb2696a4'
down_revision = '7e5e119938e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'info')
    # ### end Alembic commands ###
